### ISSUE TITLE
History file being overidden if initially empty

### ISSUE THREAD

**Issue by krystof-k** [ruby/irb#388]
## Description

I'm running multiple containers via Docker Compose with all of them mapped to a single .irb-history file which is placed on Docker volume. When they are launched, the (last?) one overrides the history.

Consider following example:

- Dockerfile:
  ```dockerfile
  FROM ruby:alpine
  RUN echo "IRB.conf[:HISTORY_FILE] = ENV['IRB_HISTORY_FILE'] if ENV['IRB_HISTORY_FILE']" >> ~/.irbrc
  ```

- docker-compose.yaml:
  ```yaml
  services:
    first:
      build:
        context: .
      volumes:
        - history:/root/.history
      environment:
        HISTFILE: /root/.history/.bash_history
        IRB_HISTORY_FILE: /root/.history/.irb-history
      command: tail -f /dev/null
    second:
      extends:
        service: first
  volumes:
    history:
  ```

- run:
  ```console
  docker compose up -d
  ```

  run in another terminal:
  ```console
  docker compose exec first irb
  puts 'first'
  ```

  run in another terminal:
  ```console
  docker compose exec second irb
  puts 'second'
  ```
  run in first terminal:
  ```console
  docker compose down
  ```

  run in first terminal:
  ```console
  docker compose run first cat /root/.history/.irb-history
  ```

  result:
  ```console
  puts 'second'
  ```

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.1.2                            
IRB version: irb 1.4.1 (2021-12-25)            
InputMethod: ReidlineInputMethod with Reline 0.3.0
.irbrc path: /root/.irbrc                      
RUBY_PLATFORM: aarch64-linux-musl              
LANG env: C.UTF-8                              
East Asian Ambiguous Width: 1 
```

## Setting Files

`~/.irbrc`:

```ruby
IRB.conf[:HISTORY_FILE] = ENV['IRB_HISTORY_FILE'] if ENV['IRB_HISTORY_FILE']
```
